### ISSUE TITLE
When I tried to load hott.idr in the REPL, it was rejected

### ISSUE THREAD

**Issue by TorosFanny** [fmota/HoTT-Idris#1]
I loaded hott.idr within the Idris's REPL.
`Idris> :load hott.idr`
and the REPL reported:
>hott.idr:115:10:When elaborating left hand side of fiber_eq:
>Can't match on fiber_eq (fiber f x p) (fiber f x p) refl refl
>Metavariables: Hott.univalence_axiom, Hott.fiber_eq
Could you please explain that to me?

**Comment by fmota** [comment]
Hi TorosFanny, I fixed fiber_eq now. This was caused by a change in the latest versions of Idris, that changed some behavior of pattern matching. Fortunately fiber_eq was the only "casualty".
